# Generated by Django 6.0.1 on 2026-01-15 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_requerente', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14)),
                ('tipo_documento', models.CharField(max_length=100)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
