# Generated by Django 6.0.1 on 2026-01-15 18:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='protocolo',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nome_requerente',
            field=models.CharField(max_length=100),
        ),
    ]
