# Generated by Django 6.0.1 on 2026-01-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_protocolo_alter_documento_nome_requerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='pdf_protocolo',
            field=models.FileField(blank=True, null=True, upload_to='protocolos/'),
        ),
    ]
