# Generated by Django 6.0.1 on 2026-01-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documento_cpf_alter_documento_nome_requerente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='nome_requerente',
            field=models.CharField(default='', max_length=150),
        ),
    ]
