# Generated by Django 6.0.1 on 2026-01-19 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_processo_nome_requerente'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('recebido', 'Recebido'), ('em_analise', 'Em analise'), ('reprovado', 'Reprovado'), ('aprovado', 'Aprovado')], default='recebido', max_length=20),
        ),
        migrations.AddField(
            model_name='processo',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processo',
            name='documento_final',
            field=models.FileField(blank=True, null=True, upload_to='documentos_final/'),
        ),
    ]
